### ISSUE TITLE
Set Date problem

### ISSUE THREAD

**Issue by vstrelianyi** [nehakadam/AnyPicker#13]
Hi. 
I have faced the following issue - when I click SET in the datepicker  - I don't see that it changes the input.
The input field is left blank.

This issue seems to appear also on the example files that you have provided. Nothing happens with the input field after you selected the date and pressed SET button.

Pls advise on this matter.

**Comment by nehakadam** [comment]
Hello @vstrelianyi,
Thank you for reporting issue. Please download and try latest version.

**Comment by vstrelianyi** [comment]
Thx for prompt fixing the issue.
Great plugin!
